MvcLogicApps/Models/ErrorViewModel.cs
namespace MvcLogicApps.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MvcLogicApps/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MvcLogicApps.Models;
using System.Diagnostics;

namespace MvcLogicApps.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MvcLogicApps/Controllers/LogicAppsController.cs
using Microsoft.AspNetCore.Mvc;
using MvcLogicApps.Services;

namespace MvcLogicApps.Controllers
{
    public class LogicAppsController : Controller
    {
        private ServiceLogicApps serivce;

        public LogicAppsController(ServiceLogicApps serivce)
        {
            this.serivce = serivce;
        }
        

        public IActionResult Mail()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Mail
            (string email, string asunto, string mensaje)
        {
            await this.serivce.SendMailAsync(email, asunto, mensaje);
            ViewData["MENSAJE"] = "Procesando Mail Logic Apps!!!";
            return View();
        }

    }
}

MvcLogicApps/Controllers/ServiceBusController.cs
using Microsoft.AspNetCore.Mvc;
using MvcLogicApps.Services;

namespace MvcLogicApps.Controllers
{
    public class ServiceBusController : Controller
    {
        private ServiceQueueBus service;

        public ServiceBusController(ServiceQueueBus service)
        {
            this.service = service;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult>
            Index(string mensaje, string accion)
        {
            if (accion.ToLower() == "enviar")
            {
                await this.service.SendMessageAsync(mensaje);
                ViewData["MENSAJE"] = "Mensaje enviado al Topic!!!";
                return View();
            }
            else
            {
                List<string> mensajes =
                    await this.service.ReceiveMessagesAsync();
                ViewData["MENSAJE"] = "Recibiendo mensajes: " + mensajes.Count;
                return View(mensajes);
            }
        }

    }
}

MvcLogicApps/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MvcLogicApps/Views/LogicApps/Mail.cshtml
<h1 style="color:blue">
    Email Logic Apps Azure
</h1>

<form method="post">
    <label>Email</label>
    <input type="text" name="email" class="form-control"/>

    <label>Asunto</label>
    <input type="text" name="asunto" class="form-control"/>

    <label>Mensaje</label>
    <textarea name="mensaje" class="form-control"></textarea>
    <button class="btn btn-info">
        Send Mail
    </button>
</form>
<h2 style="color:red">@ViewData["MENSAJE"]</h2>

MvcLogicApps/Views/ServiceBus/Index.cshtml
@model List<string>

<h1 style="color:blue">
    Azure Service Bus
</h1>

<form method="post">
    <label>Mensaje en Queue/Topic</label>
    <input type="text" name="mensaje" class="form-control" />
    <button class="btn btn-warning" value="enviar" name="accion">
        Enviar
    </button>
    <button class="btn btn-info" name="accion" value="recibir">
        Recibir mensajes
    </button>
</form>
<h2 style="color:red">@ViewData["MENSAJE"]</h2>
@if (Model != null)
{
    <ul class="list-group">
        @foreach (string msj in Model)
        {
            <li class="list-group-item">@msj</li>
        }
    </ul>
}

MvcLogicApps/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MvcLogicApps</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MvcLogicApps.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MvcLogicApps</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" 
                            asp-area="" 
                            asp-controller="LogicApps"
                            asp-action="Mail">Mail</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark"
                               asp-area=""
                               asp-controller="ServiceBus"
                               asp-action="Index">Index</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - MvcLogicApps - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>